name: Build and Deploy

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 9 * * *'  # Ежедневно в 12:00 МСК

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/alivewater-monitor:latest

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Render
      uses: render-actions/deploy@v1
      with:
        apiKey: ${{ secrets.RENDER_API_KEY }}
        serviceId: ${{ secrets.RENDER_SERVICE_ID }}
